:rootdir: ../../..
:github-readme: {rootdir}/README.adoc
:srcdir: {rootdir}/src/
:listing-caption: Listing
:revdate: {project-builddate}
:revnumber: {project-version}

include::{github-readme}[tags=vardef]

:projectpage: https://github.com/{gh-repo-owner}/{gh-repo-name}

include::{github-readme}[tags=header]

== URLs

* link:{homepage}[Project home] (this page)
* link:{projectpage}[GitHub project]
* link:{issues}[Issue tracker]

TIP: Do you want to improve this page? Please git-link:self[edit it on GitHub, edit].

== Description

In complex asciidoctorj setup (using maven or gradle), it might be usefull to know the relative path to the source directory.
The "{project-name}" extension is a preprocessor that provides this value as new attribute: `sourcedir`.

In order for the extension to work, you need to provide the configured value `sourceDir` as `sourcedir-definition` attribute.

When processing following directory, if the source directory is `docs/`:

```
docs
├── page1.adoc
└── other
    └── page2.adoc
```

Then the `sourcedir` value will be:

* empty string for `page1`
* `../` for `page2`

== Usage

The extension is published on maven central and can be directly consumed from maven or gradle.

include::{rootdir}/usage/maven-example/README.adoc[leveloffset=1, tags=maven-integration]

For a complete example, see: git-link:usage/maven-example/pom.xml[pom.xml, branch="master"]

include::{rootdir}/usage/gradle-example/README.adoc[leveloffset=1, tags=gradle-integration]

For a complete example, see: git-link:usage/gradle-example/build.gradle[build.gradle, branch="master"]

=== Which version should I use?

[cols="2*^"]
|===
| Asciidoctorj version | {project-name} version
| `1.5.x` | `1.0.0`
|===

The lattest version of this extension is built and tested with version `{asciidoctorj-version}` of `org.asciidoctor:asciidoctorj`.

== Source Code

As for any grade plugin, the source code of the plugin is available in the git-link:src/[src/] folder.

=== Build

This project is using gradle.

Command to build the sources locally:

----
./gradlew build
----

Command to deploy to your local maven repository:

----
./gradlew publishToMavenLocal
----

Command to build the documentation page:

----
./gradlew asciidoctor
----

The output of this command is an HTML page located at `<git repo root>/build/docs/html5/index.html`.

==== For project maintainers

`signing.gnupg.keyName` and `signing.gnupg.passphrase` are expected to be set in your local `gradle.properties` file to be able to sign.
`sonatypeUser` and `sonatypePassword` are expected to be set in order to be able to publish to a distant repository.
					
Command to build and publish the result in a distant maven repository:

----
./gradlew publish
----

Command to upload the documentation page on GitHub pages:

----
./gradlew gitPublishPush
----

Command to perform a release:

----
./gradlew release -Prelease.useAutomaticVersion=true
----

==== Using ssh-agent

Some tasks requires to push into the distant git repository (release task or updating the `gh-pages` branch).
If they are failing with errors like this:
----
org.eclipse.jgit.api.errors.TransportException: ... Permission denied (publickey).
---- 

Then `ssh-agent` can be used.
----
eval `ssh-agent -s`
ssh-add ~/.ssh/id_rsa
----
(link:https://superuser.com/a/990447/[source] for this approach)


include::{github-readme}[tags=contact-section]

include::{github-readme}[tags=license-section]

